### PR TITLE
Random solver failure

### PR DESCRIPTION
**Pull request by arthur-brown**
When I run the file case_studies/new_york_heli.py, I sometimes get an UNKNOWN error from MOSEK:
> RuntimeWarning: final status of solver 'mosek' was 'UNKNOWN', not 'optimal'.

When I run the debugger:

`problem.debug()`

The model solves, but with one variable relaxed to a degree so small it is imperceptible. For example:
> weight_fraction_OnDemandAircraft.3/Structure.3: relaxed from 0.5 to 0.5

This seems to happen randomly. Sometimes it happens; sometimes it doesn't; no changes are made to the code in between. I suspect this is a solver convergence problem. Also, it happens in other files/studies as well; I only selected case_studies/new_york_heli.py as an example.

### CODE REVIEW

**Comment by bqpd** [comment]
Hmm, does the model solve if you just [bound](http://gpkit.readthedocs.io/en/latest/debugging.html#dual-infeasibility) it, without doing relaxation?

**Comment by arthur-brown** [comment]
I'm trying this:

`from gpkit.constraints.bounded import Bounded`

`problem = Model(MissionCost["cost_per_trip"], Bounded([Aircraft, SizingMission, RevenueMission, DeadheadMission, MissionCost]))`
`problem.substitutions.update(problem_subDict)`
`solution = problem.solve(verbosity=0)`

This works, but I'm not sure why it is necessary. Also, it would be an issue if there is some other error in my code that Bounded makes harder to find. Finally, is there a way of not printing the bounds warning?

**Comment by bqpd** [comment]
The bounds warnings are probably telling you what you need to fix in your model...

**Comment by arthur-brown** [comment]
The trouble is that a different set of variables are bounded on each run, so I have no idea which set to look at. I've added Bounded to eVTOL/aircraft_models.py to illustrate this effect. The first time I run it, I get the following:

> Solves with these variables bounded:
 sensitive to lower bound: CP_OnDemandRevenueMission.2/Hover.15/RotorsAero.15, cost_per_mission_OnDemandMissionCost.2/DeadheadMissionCost.2/OperatingExpenses.5/EnergyCost.5, IOC_OnDemandMissionCost.2/RevenueMissionCost.2/OperatingExpenses.4, T_perRotor_OnDemandDeadheadMission.2/Hover.16/RotorsAero.16, Q_perRotor_OnDemandRevenueMission.2/Hover.15/RotorsAero.15, segment_range_OnDemandRevenueMission.2/LevelFlight.10, P_OnDemandSizingMission.2/Hover.12/BatteryPerformance.20, E_OnDemandDeadheadMission.2_(1,), P_OnDemandDeadheadMission.2/LevelFlight.11/BatteryPerformance.28, P_{tailRotor}_OnDemandDeadheadMission.2/LevelFlight.11
 sensitive to upper bound: Cl_mean_OnDemandRevenueMission.2/Hover.14/RotorsAero.14, E_OnDemandDeadheadMission.2_(2,), wrap_rate_OnDemandMissionCost.2/DeadheadMissionCost.2/OperatingExpenses.5/MaintenanceCost.5, t_OnDemandSizingMission.2/Hover.12, t_{flight}_OnDemandRevenueMission.2, W_{mission}_OnDemandDeadheadMission.2, IOC_OnDemandMissionCost.2/RevenueMissionCost.2/OperatingExpenses.4, E_OnDemandRevenueMission.2/Hover.15/BatteryPerformance.26, cost_per_mission_OnDemandMissionCost.2/DeadheadMissionCost.2/CapitalExpenses.5, P_OnDemandRevenueMission.2/LevelFlight.10/BatteryPerformance.25, purchase_price_OnDemandAircraft.2, P_{battery}_OnDemandSizingMission.2_(0,)

But when I run it again (with no changes to the code), I get this:

> Solves with these variables bounded:
 sensitive to lower bound: P_{tailRotor}_OnDemandSizingMission.3/Hover.19, t_OnDemandDeadheadMission.3/Hover.23, V_{loiter}_OnDemandSizingMission.3, T/A_OnDemandSizingMission.3, FOM_OnDemandSizingMission.3/Hover.19/RotorsAero.19, MT_OnDemandRevenueMission.3_(0,), VT_OnDemandDeadheadMission.3/Hover.22/RotorsAero.22, mission_range_OnDemandSizingMission.3, W_OnDemandDeadheadMission.3/Passengers.11, V_OnDemandSizingMission.3/LevelFlight.13
 sensitive to upper bound: VT_OnDemandDeadheadMission.3_(0,), MT_OnDemandSizingMission.3_(0,), P_{out}_OnDemandRevenueMission.3/Hover.20/ElectricalSystemPerformance.34, MT_OnDemandDeadheadMission.3/Hover.22/RotorsAero.22, T/A_OnDemandDeadheadMission.3/Hover.23, MT_OnDemandDeadheadMission.3/Hover.23/RotorsAero.23, CT_OnDemandRevenueMission.3_(1,), V_OnDemandSizingMission.3/LevelFlight.13, P_{out}_OnDemandSizingMission.3/LevelFlight.13/ElectricalSystemPerformance.32, Q_perRotor_OnDemandDeadheadMission.3/Hover.22/RotorsAero.22, cost_per_mission_OnDemandMissionCost.3/DeadheadMissionCost.3/OperatingExpenses.7/MaintenanceCost.7, T/A_OnDemandRevenueMission.3/Hover.20/RotorsAero.20

which is a different set of variables, so I'm not sure where to start in fixing it.

**Comment by bqpd** [comment]
Mm that's frustrating. So, there can be multiple sets of bounded variables that will solve this problem...I'd recommend trying to figure out if there's a pattern, or if there's obvious bounds missing from any of the variables that show up in both lists.

**Comment by bqpd** [comment]
test models please

**Comment by bqpd** [comment]
Actually, try updating your version of gpkit? This seems to solve just fine on my computer, with convexengineering/gpkit@2fa8b1f and using mosek as the solver...

**Comment by arthur-brown** [comment]
I don't seem to have any problems running aircraft_models.py without Bounded() (at least not so far), but I've tried updating gpkit and I still have the same problem in case_studies/new_york_heli. I have tried the following:

> cd ~/gpkit
git pull origin master
cd ..
pip install -e gpkit

I believe that this should update gpkit. All the tests work, but I am left with exactly the same issue in case_studies/new_york_heli/new_york_heli.py if I try this.

**Comment by arthur-brown** [comment]
UPDATE: I've tried running this on my laptop, using the same set of commands to update gpkit. The random solver errors still occur, although they appear to happen less often than on my desktop.

**Comment by arthur-brown** [comment]
This problem has been solved. The issue was with three parameters that are nearly zero, and that appear in products:

> tailRotor_power_fraction_hover = Variable("tailRotor_power_fraction_hover", 0.0001,"-","Tail-rotor power as a fraction of lifting-rotors power")
tailRotor_power_fraction_levelFlight = Variable("tailRotor_power_fraction_levelFlight", 0.0001,"-","Tail-rotor power as a fraction of lifting-rotors power")
N_passengers = Variable("N_{passengers}","-","Number of passengers")

In some circumstances, it is desirable to set these parameters to 0 (usually via substitution). For example, configurations with no tail rotor should have zero tail-rotor power fractions; the deadhead mission is also flown with no passengers (N_passengers = 0). However, all three of these terms appear in products; GPkit cannot handle them if they are set to exactly 0. 

This was previously solved by setting the parameters to a small positive number. However, if the number is small enough (but still positive), GPkit and MOSEK will have numerical issues. This leads directly to the occasional solver failures documented in this pull request. 

The problem is easily avoided by using larger (but still small) values. The tail-rotor power fractions were increased from 0.0001 to 0.001, while N_passengers (deadhead mission) was increased from 0.00001 to 0.001. This has a negligible impact of the objective function (less than 1¢), while no random solver failures have occurred in any of the codes in which this change was implemented so far.

**Pull request closed without merging**
